openapi: 3.0.0
info:
  title: openapi.v1
  version: '1.0'
servers:
  - url: 'https://connectivity.astraiot.co.uk:3000/devices'
    description: GeoFence API
paths: {}
components:
  schemas: {}
  securitySchemes:
    Bearer:
      name: API Key
      type: apiKey
      in: header
