openapi: 3.0.0
tags:
  - name: auth
    description: Authentication and authorization related operations.
info:
  title: Auth
  version: '1.0'
  description: API that provides authentication to all applying clients.
  contact:
    name: Miguel Vera
    email: miguel@astraiot.co.uk
servers:
  - url: 'https://connectivity.gps-telematics.co.uk:3000/auth'
    description: Backend
paths:
  /token:
    post:
      summary: Obtain authentication token
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/oauth2token.v1.yaml
        '401':
          description: Wrong ClientId or ApiKey.
          headers: {}
      description: This endpoint provides an OAuth2 token to use for authentication of subsequent requests to this backend.
      security:
        - Basic Access Authentication: []
      operationId: getAuthToken
      tags:
        - auth
    parameters: []
components:
  schemas: {}
  securitySchemes:
    Basic Access Authentication:
      type: http
      scheme: Basic
      description: 'Provide a "ClientId:ApiKey" string encoded in Base64 and add the string "Basic " to the front.'
